name: image
version: 4.1.4
description: >-
  Dart Image Library provides server and web apps the ability to load, manipulate,
  and save images with various image file formats.
homepage: https://github.com/brendan-duncan/image
documentation: https://github.com/brendan-duncan/image/blob/main/doc/README.md

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  meta: ^1.15.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^2.2.0
  build_web_compilers: ^4.0.0
  http: ^1.0.0
  lints: ^5.0.0
  test: ^1.25.0
